# docker-compose.yml

services:
  solasola:
    image: castika/solasola:latest
    container_name: solasola_web
    restart: unless-stopped
    ports:
      - "5656:5656"
    volumes:
      - ./Music:/app/output
      - ./AI_Models:/app/user_models
      - cache:/app/cache
    environment:
      - HF_HOME=/app/user_models
      - HOST_AI_MODELS_DIR=/app/user_models
      - TORCH_HOME=/app/user_models/torch
      - HOST_MUSIC_DIR=/app/output
    command: python -m solasola.app --no-debug

volumes:
  cache:
