# This workflow automatically validates code, builds, and scans the Docker image
# whenever a pull request is opened against the 'main' branch.
# Use this with branch protection rules to prevent merging faulty code.

# This workflow automatically validates code, builds, and scans the Docker image
# whenever a pull request is opened against the 'main' branch.
# Use this with branch protection rules to prevent merging faulty code.

name: Validate Pull Request

on:
  pull_request:
    branches: [ "main" ]
    # --- OPTIMIZATION: Run this workflow ONLY when relevant files are changed ---
    # This prevents the long validation process from running on simple changes
    # to documentation (like README.md) or other non-code files.
    paths:
      - 'solasola/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'Dockerfile'
      - '.github/workflows/docker-scan.yml'

permissions:
  contents: read          # To check out the repository's code.
  security-events: write  # To upload the SARIF results from Docker Scout to the GitHub Security tab.
  pull-requests: write    # To post status checks back to the pull request.

jobs:
  validate:
    name: Validate, Build, and Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Debug - Verify File Existence
        working-directory: .
        run: |
          echo "--- Current Directory ---"
          pwd
          echo "--- Repository Root Contents ---"
          ls -la
          echo "--- Searching for pyproject.toml ---"
          find . -name "pyproject.toml"

      - name: Maximize build disk space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: true

      - name: Set up Python and Poetry
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        # This action does not use working-directory, it installs poetry globally for the runner

      - name: Install dependencies
        working-directory: .
        run: |
          poetry install

      - name: Lint code with flake8
        working-directory: .
        run: poetry run flake8 solasola/

      - name: Run tests with pytest
        working-directory: .
        run: poetry run pytest

      - name: Check for forbidden files tracked by Git
        working-directory: .
        run: |
          # This script explicitly checks for files that should never be committed, based on .gitignore rules.
          # Hardcoding these patterns makes the workflow's security checks self-contained and explicit.
          FORBIDDEN_PATTERNS=(
            "__pycache__/"
            "\.py[cod]$"
            "\\$py\.class$"
            "\.venv/"
            "env/"
            "venv/"
            "build/"
            "dist/"
            "\.egg-info/"
            "\.vscode/"
            "\.pytest_cache/"
            "\.coverage$"
            "\.DS_Store$"
            "Thumbs\.db$"
            "\.log$"
            "requirements\.txt$"
            "dog\.sh$"
            "dogwin\.sh$"
            "publish\.sh$"
            "solasola-test-image\.tar$"
          )
          # Find forbidden files and replace newlines with spaces to ensure single-line output for the error message.
          FORBIDDEN_FILES=$(git ls-files | grep -E "$(IFS=\| ; echo "${FORBIDDEN_PATTERNS[*]}")" | tr '\n' ' ')

          if [ -n "$FORBIDDEN_FILES" ]; then
            # Use a GitHub Actions error command to force the output to be visible.
            # This will create a clear annotation on the pull request.
            echo "::error::Forbidden files found in Git index: $FORBIDDEN_FILES"
            exit 1
          fi
          echo "✅ No forbidden files are being tracked by Git."

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image locally for scanning
        working-directory: .
        run: |
          docker buildx build \
            --no-cache \
            --platform linux/amd64 \
            --cache-to type=inline \
            --progress=plain \
            --tag castika/solasola:ci-scan \
            --load .

      - name: Scan image with Docker Scout
        working-directory: .
        run: |
          docker scout cves castika/solasola:ci-scan \
            --exit-code \
            --only-severity critical,high \
            --format sarif \
            --output scout-report.sarif

      - name: Upload Docker Scout SARIF report
        uses: github/codeql-action/upload-sarif@v3
        working-directory: .
        with:
          sarif_file: scout-report.sarif
