# This workflow builds the Docker image and pushes it to Docker Hub
# when a push event occurs on the 'main' branch (e.g., after a PR is merged).

name: Docker Image Publishing

on:
  push:
    branches: [ "main" ]
    # CRITICAL SAFETY FEATURE: Only publish when application code changes
    paths:
      - 'solasola/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'Dockerfile'
      - '.github/workflows/docker-publish.yml'

jobs:
  build-and-publish:
    name: Build and Publish Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up disk space on runner
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version and set Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: castika/solasola
          tags: |
            # --- DEFINITIVE FIX: Use 'semver' type to correctly parse version tags like 'v0.1.0.21' ---
            # This correctly handles the 'v' prefix from the version.json file.
            type=semver,pattern={{json:solasola/version.json:version}}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true