# This workflow automatically validates code, builds, and scans the Docker image
# whenever a pull request is opened against the 'main' branch.
# Use this with branch protection rules to prevent merging faulty code.

# This workflow automatically validates code, builds, and scans the Docker image
# whenever a pull request is opened against the 'main' branch.
# Use this with branch protection rules to prevent merging faulty code.

name: Validate Pull Request

on:
  pull_request:
    branches: [ "main" ]
    # --- OPTIMIZATION: Run this workflow ONLY when relevant files are changed ---
    # This prevents the long validation process from running on simple changes
    # to documentation (like README.md) or other non-code files.
    paths:
      - 'solasola/**'
      - 'tests/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'Dockerfile'
      - '.github/workflows/docker-scan.yml'

permissions:
  contents: read          # To check out the repository's code.
  security-events: write  # To upload the SARIF results from Docker Scout to the GitHub Security tab.
  pull-requests: write    # To post status checks back to the pull request.

jobs:
  # This is the main validation job.
  validate:
    name: Validate, Build, and Scan
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build disk space
        uses: easimon/maximize-build-space@v10
        with:
          # Reserve 2GB for the runner's root filesystem to prevent it from
          # running out of space when writing its own final logs.
          root-reserve-mb: 2048
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: true

      - name: Analyze Disk Usage After Cleanup
        # This step now performs two functions:
        # 1. Manually remove additional large toolchains that `maximize-build-space` might miss.
        # 2. Analyze the remaining disk usage to confirm space has been freed.
        run: |
          echo "--- Manually removing additional large toolchains ---"
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/lib/jvm
          echo "--- Additional cleanup complete ---"

          echo "--- Analyzing disk usage on the runner's root filesystem ---"
          echo "The following are the 30 largest files/directories on the root partition:"
          # Use 'du' to find disk usage, sort by human-readable size, and show the top 30.
          # This helps identify what is consuming space on the small root partition.
          sudo du -ah / --exclude=/proc --exclude=/dev --exclude=/sys --exclude=${{ github.workspace }} | sort -rh | head -n 30
          echo "----------------------------------------------------------------"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python and Poetry
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Configure Poetry to use a local virtualenv
        working-directory: .
        run: poetry config virtualenvs.in-project true

      - name: Check available disk space before install
        working-directory: .
        run: |
          echo "--- Available Disk Space ---"
          echo "Workspace:"
          df -h .
          echo "Root:"
          df -h /
          echo "Runner Home:"
          df -h /home/runner

      - name: Install dependencies
        working-directory: .
        env:
          TMPDIR: ${{ github.workspace }}/.tmp
          # --- DEFINITIVE FIX: Redirect poetry and pip caches to the large workspace volume ---
          POETRY_CACHE_DIR: ${{ github.workspace }}/.poetry-cache
          PIP_CACHE_DIR: ${{ github.workspace }}/.pip-cache
        run: |
          mkdir -p .tmp .poetry-cache .pip-cache
          poetry install

      - name: Check available disk space after install
        working-directory: .
        run: |
          echo "--- Available Disk Space After Install ---"
          df -h .

      - name: Lint code with flake8
        working-directory: .
        run: poetry run flake8 solasola/

      - name: Run tests with pytest
        working-directory: .
        run: poetry run pytest

      - name: Clean up test artifacts
        working-directory: .
        run: |
          rm -rf .pytest_cache

      - name: Check for forbidden files tracked by Git
        working-directory: .
        run: |
          # This script explicitly checks for files that should never be committed, based on .gitignore rules.
          # Hardcoding these patterns makes the workflow's security checks self-contained and explicit.
          FORBIDDEN_PATTERNS=(
            "__pycache__/"
            "\.py[cod]$"
            "\\$py\.class$"
            "\.venv/"
            "env/"
            "venv/"
            "build/"
            "dist/"
            "\.egg-info/"
            "\.vscode/"
            "\.pytest_cache/"
            "\.coverage$"
            "\.DS_Store$"
            "Thumbs\.db$"
            "\.log$"
            "requirements\.txt$"
            "dog\.sh$"
            "dogwin\.sh$"
            "publish\.sh$"
            "solasola-test-image\.tar$"
          )
          # Find forbidden files and replace newlines with spaces to ensure single-line output for the error message.
          FORBIDDEN_FILES=$(git ls-files | grep -E "$(IFS=\| ; echo "${FORBIDDEN_PATTERNS[*]}")" | tr '\n' ' ')

          if [ -n "$FORBIDDEN_FILES" ]; then
            # Use a GitHub Actions error command to force the output to be visible.
            # This will create a clear annotation on the pull request.
            echo "::error::Forbidden files found in Git index: $FORBIDDEN_FILES"
            exit 1
          fi
          echo "✅ No forbidden files are being tracked by Git."

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image locally for scanning
        working-directory: .
        run: |
          docker buildx build \
            --no-cache \
            --platform linux/amd64 \
            --cache-to type=inline \
            --progress=plain \
            --tag castika/solasola:ci-scan \
            --load .

      - name: Prune Docker Builder Cache
        # --- DEFINITIVE FIX: Always run this step, even if the build fails ---
        # This ensures that we clean up build cache to make space for the runner's own logs.
        if: always()
        run: |
          echo "Pruning Docker builder cache to free up space..."
          docker builder prune -af

      - name: Scan image with Docker Scout
        run: |
          docker scout cves castika/solasola:ci-scan \
            --exit-code \
            --only-severity critical,high \
            --format sarif \
            --output scout-report.sarif

      - name: Upload Docker Scout SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: scout-report.sarif

  # This job runs regardless of whether the 'validate' job succeeded or failed.
  # It's the equivalent of a 'finally' block in a try-catch statement.
  post-cleanup:
    name: Post-Job Cleanup and Diagnostics
    runs-on: ubuntu-latest
    # The 'if: always()' condition ensures this job runs even if 'validate' fails.
    if: always()
    # This job needs the results of the 'validate' job to decide what to do.
    needs: validate

    steps:
      - name: Display Final Disk Space
        run: |
          echo "--- Final Disk Space on Runner ---"
          df -h
          echo "This information is useful for diagnosing 'No space left on device' errors."
